export function getHtml(): string {
  return [
    "<!DOCTYPE html>",
    '<html lang="en">',
    "<head>",
    '<meta charset="UTF-8">',
    '<meta name="viewport" content="width=device-width, initial-scale=1.0">',
    "<title>Kanban Board</title>",
    '<link rel="preconnect" href="https://fonts.googleapis.com">',
    '<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>',
    '<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet">',
    "<style>",
    getStyles(),
    "</style>",
    "</head>",
    "<body>",
    '<div id="app">',
    '<header class="toolbar">',
    '<h1 class="toolbar-title">Kanban Board</h1>',
    '<button class="btn btn-primary" id="add-list-btn" aria-label="Add new list">+ Add List</button>',
    "</header>",
    '<div class="board" id="board">',
    '<div class="board-loading">Loading board...</div>',
    "</div>",
    '<div class="error-banner" id="error-banner" role="alert" style="display:none"></div>',
    "</div>",
    "<script>",
    getScript(),
    "</script>",
    "</body>",
    "</html>",
  ].join("\n");
}

function getStyles(): string {
  return [
    ":root {",
    "  --bg: #f0f2f5;",
    "  --card-bg: #ffffff;",
    "  --text: #1a1a2e;",
    "  --text-secondary: #6b7280;",
    "  --border: #e2e5e9;",
    "  --shadow: 0 1px 3px rgba(0,0,0,0.08);",
    "  --shadow-hover: 0 2px 8px rgba(0,0,0,0.12);",
    "  --radius: 8px;",
    "  --radius-sm: 6px;",
    "  --list-width: 300px;",
    "  --font: 'Inter', -apple-system, BlinkMacSystemFont, sans-serif;",
    "}",
    "",
    "*, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }",
    "",
    "body {",
    "  font-family: var(--font);",
    "  background: var(--bg);",
    "  color: var(--text);",
    "  min-height: 100vh;",
    "  overflow-x: auto;",
    "}",
    "",
    ".toolbar {",
    "  display: flex;",
    "  align-items: center;",
    "  justify-content: space-between;",
    "  padding: 16px 24px;",
    "  background: #ffffff;",
    "  border-bottom: 1px solid var(--border);",
    "  position: sticky;",
    "  top: 0;",
    "  z-index: 10;",
    "}",
    "",
    ".toolbar-title {",
    "  font-size: 20px;",
    "  font-weight: 700;",
    "  color: var(--text);",
    "}",
    "",
    ".board {",
    "  display: flex;",
    "  gap: 16px;",
    "  padding: 24px;",
    "  min-height: calc(100vh - 65px);",
    "  align-items: flex-start;",
    "  overflow-x: auto;",
    "}",
    "",
    ".board-loading {",
    "  color: var(--text-secondary);",
    "  font-size: 14px;",
    "  padding: 40px;",
    "}",
    "",
    ".list {",
    "  flex: 0 0 var(--list-width);",
    "  background: var(--card-bg);",
    "  border-radius: var(--radius);",
    "  box-shadow: var(--shadow);",
    "  display: flex;",
    "  flex-direction: column;",
    "  max-height: calc(100vh - 110px);",
    "}",
    "",
    ".list-header {",
    "  padding: 12px 14px;",
    "  border-radius: var(--radius) var(--radius) 0 0;",
    "  display: flex;",
    "  align-items: center;",
    "  justify-content: space-between;",
    "  gap: 8px;",
    "  min-height: 48px;",
    "}",
    "",
    ".list-header-left {",
    "  display: flex;",
    "  align-items: center;",
    "  gap: 8px;",
    "  flex: 1;",
    "  min-width: 0;",
    "}",
    "",
    ".list-title {",
    "  font-size: 14px;",
    "  font-weight: 600;",
    "  color: #fff;",
    "  cursor: pointer;",
    "  white-space: nowrap;",
    "  overflow: hidden;",
    "  text-overflow: ellipsis;",
    "  padding: 4px 0;",
    "  min-height: 36px;",
    "  display: flex;",
    "  align-items: center;",
    "}",
    "",
    ".list-count {",
    "  font-size: 12px;",
    "  font-weight: 500;",
    "  color: rgba(255,255,255,0.8);",
    "  background: rgba(255,255,255,0.2);",
    "  padding: 2px 8px;",
    "  border-radius: 10px;",
    "  white-space: nowrap;",
    "}",
    "",
    ".list-cards {",
    "  padding: 8px;",
    "  display: flex;",
    "  flex-direction: column;",
    "  gap: 8px;",
    "  overflow-y: auto;",
    "  flex: 1;",
    "}",
    "",
    ".list-footer {",
    "  padding: 8px;",
    "  border-top: 1px solid var(--border);",
    "}",
    "",
    ".card {",
    "  background: var(--card-bg);",
    "  border: 1px solid var(--border);",
    "  border-radius: var(--radius-sm);",
    "  padding: 10px 12px;",
    "  box-shadow: var(--shadow);",
    "  cursor: grab;",
    "  transition: box-shadow 0.15s ease;",
    "}",
    "",
    ".card:hover { box-shadow: var(--shadow-hover); }",
    "",
    ".card.dragging { opacity: 0.5; }",
    "",
    ".card-title {",
    "  font-size: 13px;",
    "  font-weight: 500;",
    "  margin-bottom: 4px;",
    "  word-break: break-word;",
    "}",
    "",
    ".card-desc {",
    "  font-size: 12px;",
    "  color: var(--text-secondary);",
    "  white-space: nowrap;",
    "  overflow: hidden;",
    "  text-overflow: ellipsis;",
    "  margin-bottom: 8px;",
    "}",
    "",
    ".card-actions {",
    "  display: flex;",
    "  gap: 4px;",
    "  flex-wrap: wrap;",
    "}",
    "",
    ".btn {",
    "  display: inline-flex;",
    "  align-items: center;",
    "  justify-content: center;",
    "  min-height: 36px;",
    "  padding: 6px 12px;",
    "  font-size: 13px;",
    "  font-family: var(--font);",
    "  font-weight: 500;",
    "  border: 1px solid var(--border);",
    "  border-radius: var(--radius-sm);",
    "  background: #fff;",
    "  color: var(--text);",
    "  cursor: pointer;",
    "  transition: all 0.15s ease;",
    "  white-space: nowrap;",
    "}",
    "",
    ".btn:hover { background: #f5f5f5; }",
    ".btn:disabled { opacity: 0.4; cursor: not-allowed; }",
    "",
    ".btn-sm {",
    "  min-height: 28px;",
    "  padding: 3px 8px;",
    "  font-size: 12px;",
    "}",
    "",
    ".btn-primary {",
    "  background: var(--text);",
    "  color: #fff;",
    "  border-color: var(--text);",
    "}",
    ".btn-primary:hover { background: #333; }",
    "",
    ".btn-danger { color: #dc2626; border-color: #fca5a5; }",
    ".btn-danger:hover { background: #fef2f2; }",
    "",
    ".btn-ghost {",
    "  border: none;",
    "  background: transparent;",
    "  color: rgba(255,255,255,0.9);",
    "}",
    ".btn-ghost:hover { background: rgba(255,255,255,0.15); }",
    "",
    ".btn-move {",
    "  min-height: 28px;",
    "  padding: 3px 6px;",
    "  font-size: 11px;",
    "  border-color: #d1d5db;",
    "}",
    "",
    "input, textarea {",
    "  font-family: var(--font);",
    "  font-size: 13px;",
    "  padding: 8px 10px;",
    "  border: 1px solid var(--border);",
    "  border-radius: var(--radius-sm);",
    "  width: 100%;",
    "  outline: none;",
    "  min-height: 36px;",
    "}",
    "input:focus, textarea:focus { border-color: #6366f1; box-shadow: 0 0 0 2px rgba(99,102,241,0.15); }",
    "",
    "textarea { resize: vertical; min-height: 60px; }",
    "",
    ".inline-form {",
    "  display: flex;",
    "  flex-direction: column;",
    "  gap: 6px;",
    "}",
    "",
    ".inline-form-row {",
    "  display: flex;",
    "  gap: 6px;",
    "}",
    "",
    ".confirm-bar {",
    "  display: flex;",
    "  align-items: center;",
    "  gap: 6px;",
    "  font-size: 12px;",
    "  color: #dc2626;",
    "  padding: 4px 0;",
    "}",
    "",
    ".error-banner {",
    "  position: fixed;",
    "  bottom: 16px;",
    "  left: 50%;",
    "  transform: translateX(-50%);",
    "  background: #dc2626;",
    "  color: #fff;",
    "  padding: 10px 20px;",
    "  border-radius: var(--radius);",
    "  font-size: 13px;",
    "  z-index: 100;",
    "  max-width: 90%;",
    "}",
    "",
    ".drop-zone {",
    "  min-height: 4px;",
    "  border-radius: 2px;",
    "  transition: all 0.15s ease;",
    "}",
    ".drop-zone.active {",
    "  min-height: 40px;",
    "  background: rgba(99,102,241,0.1);",
    "  border: 2px dashed #6366f1;",
    "  margin: 4px 0;",
    "}",
  ].join("\n");
}

function getScript(): string {
  return [
    "(function() {",
    "  'use strict';",
    "",
    "  var LIST_COLORS = ['#6366f1','#8b5cf6','#ec4899','#f59e0b','#10b981','#06b6d4','#3b82f6','#ef4444'];",
    "  var boardEl = document.getElementById('board');",
    "  var errorBanner = document.getElementById('error-banner');",
    "  var addListBtn = document.getElementById('add-list-btn');",
    "  var boardData = [];",
    "  var dragCardId = null;",
    "",
    "  function showError(msg) {",
    "    errorBanner.textContent = msg;",
    "    errorBanner.style.display = 'block';",
    "    setTimeout(function() { errorBanner.style.display = 'none'; }, 4000);",
    "  }",
    "",
    "  function api(method, path, body) {",
    "    var opts = { method: method, headers: {} };",
    "    if (body) {",
    "      opts.headers['Content-Type'] = 'application/json';",
    "      opts.body = JSON.stringify(body);",
    "    }",
    "    return fetch(path, opts).then(function(r) {",
    "      return r.json().then(function(data) {",
    "        if (!r.ok) throw new Error(data.error || 'Request failed');",
    "        return data;",
    "      });",
    "    });",
    "  }",
    "",
    "  function loadBoard() {",
    "    return api('GET', '/api/lists').then(function(data) {",
    "      boardData = data.lists || [];",
    "      render();",
    "    }).catch(function(err) {",
    "      showError('Failed to load board: ' + err.message);",
    "    });",
    "  }",
    "",
    "  function getListIndex(listId) {",
    "    for (var i = 0; i < boardData.length; i++) {",
    "      if (boardData[i].id === listId) return i;",
    "    }",
    "    return -1;",
    "  }",
    "",
    "  function render() {",
    "    var html = '';",
    "    for (var i = 0; i < boardData.length; i++) {",
    "      html += renderList(boardData[i], i);",
    "    }",
    "    boardEl.innerHTML = html;",
    "    bindListEvents();",
    "  }",
    "",
    "  function renderList(list, idx) {",
    "    var color = LIST_COLORS[idx % LIST_COLORS.length];",
    "    var cards = list.cards || [];",
    "    var h = '';",
    "    h += '<div class=\"list\" data-list-id=\"' + list.id + '\">';",
    "    h += '<div class=\"list-header\" style=\"background:' + color + '\">';",
    "    h += '<div class=\"list-header-left\">';",
    "    h += '<span class=\"list-title\" data-action=\"rename-list\" data-list-id=\"' + list.id + '\" title=\"Click to rename\">' + esc(list.title) + '</span>';",
    "    h += '<span class=\"list-count\">' + cards.length + '</span>';",
    "    h += '</div>';",
    "    h += '<button class=\"btn btn-ghost btn-sm\" data-action=\"delete-list\" data-list-id=\"' + list.id + '\" aria-label=\"Delete list ' + esc(list.title) + '\">X</button>';",
    "    h += '</div>';",
    "    h += '<div class=\"list-cards\" data-list-id=\"' + list.id + '\">';",
    "    for (var j = 0; j < cards.length; j++) {",
    "      h += renderCard(cards[j], list.id, idx);",
    "    }",
    "    h += '</div>';",
    "    h += '<div class=\"list-footer\">';",
    "    h += '<button class=\"btn btn-sm\" style=\"width:100%\" data-action=\"show-add-card\" data-list-id=\"' + list.id + '\" aria-label=\"Add card to ' + esc(list.title) + '\">+ Add Card</button>';",
    "    h += '</div>';",
    "    h += '</div>';",
    "    return h;",
    "  }",
    "",
    "  function renderCard(card, listId, listIdx) {",
    "    var h = '';",
    "    h += '<div class=\"card\" draggable=\"true\" data-card-id=\"' + card.id + '\" data-list-id=\"' + listId + '\">';",
    "    h += '<div class=\"card-title\">' + esc(card.title) + '</div>';",
    "    if (card.description) {",
    "      h += '<div class=\"card-desc\">' + esc(card.description) + '</div>';",
    "    }",
    "    h += '<div class=\"card-actions\">';",
    "    h += '<button class=\"btn btn-sm btn-move\" data-action=\"move-left\" data-card-id=\"' + card.id + '\"' + (listIdx === 0 ? ' disabled' : '') + ' aria-label=\"Move card left\">&larr; Left</button>';",
    "    h += '<button class=\"btn btn-sm btn-move\" data-action=\"move-right\" data-card-id=\"' + card.id + '\"' + (listIdx === boardData.length - 1 ? ' disabled' : '') + ' aria-label=\"Move card right\">Right &rarr;</button>';",
    "    h += '<button class=\"btn btn-sm\" data-action=\"edit-card\" data-card-id=\"' + card.id + '\" aria-label=\"Edit card\">Edit</button>';",
    "    h += '<button class=\"btn btn-sm btn-danger\" data-action=\"delete-card\" data-card-id=\"' + card.id + '\" aria-label=\"Delete card\">Delete</button>';",
    "    h += '</div>';",
    "    h += '</div>';",
    "    return h;",
    "  }",
    "",
    "  function esc(s) {",
    "    if (!s) return '';",
    "    return String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/\"/g,'&quot;');",
    "  }",
    "",
    "  function findCard(cardId) {",
    "    for (var i = 0; i < boardData.length; i++) {",
    "      var cards = boardData[i].cards || [];",
    "      for (var j = 0; j < cards.length; j++) {",
    "        if (cards[j].id === cardId) return { card: cards[j], listIdx: i, cardIdx: j };",
    "      }",
    "    }",
    "    return null;",
    "  }",
    "",
    "  // Event delegation",
    "  function bindListEvents() {",
    "    // Drag and drop",
    "    var allCards = boardEl.querySelectorAll('.card[draggable]');",
    "    for (var ci = 0; ci < allCards.length; ci++) {",
    "      (function(cardEl) {",
    "        cardEl.addEventListener('dragstart', function(e) {",
    "          dragCardId = parseInt(cardEl.getAttribute('data-card-id'), 10);",
    "          cardEl.classList.add('dragging');",
    "          e.dataTransfer.effectAllowed = 'move';",
    "        });",
    "        cardEl.addEventListener('dragend', function() {",
    "          cardEl.classList.remove('dragging');",
    "          dragCardId = null;",
    "          clearDropZones();",
    "        });",
    "      })(allCards[ci]);",
    "    }",
    "",
    "    var listCardAreas = boardEl.querySelectorAll('.list-cards');",
    "    for (var li = 0; li < listCardAreas.length; li++) {",
    "      (function(area) {",
    "        area.addEventListener('dragover', function(e) {",
    "          e.preventDefault();",
    "          e.dataTransfer.dropEffect = 'move';",
    "        });",
    "        area.addEventListener('drop', function(e) {",
    "          e.preventDefault();",
    "          if (dragCardId === null) return;",
    "          var targetListId = parseInt(area.getAttribute('data-list-id'), 10);",
    "          var targetCards = area.querySelectorAll('.card');",
    "          var pos = targetCards.length;",
    "          api('POST', '/api/cards/' + dragCardId + '/move', { target_list_id: targetListId, position: pos })",
    "            .then(function() { return loadBoard(); })",
    "            .catch(function(err) { showError('Move failed: ' + err.message); });",
    "        });",
    "      })(listCardAreas[li]);",
    "    }",
    "  }",
    "",
    "  function clearDropZones() {",
    "    var zones = boardEl.querySelectorAll('.drop-zone');",
    "    for (var z = 0; z < zones.length; z++) zones[z].classList.remove('active');",
    "  }",
    "",
    "  // Global click delegation",
    "  document.addEventListener('click', function(e) {",
    "    var target = e.target;",
    "    var action = target.getAttribute('data-action');",
    "    if (!action) {",
    "      // Check parent",
    "      if (target.parentElement) {",
    "        action = target.parentElement.getAttribute('data-action');",
    "        if (action) target = target.parentElement;",
    "      }",
    "    }",
    "    if (!action) return;",
    "",
    "    var listId = target.getAttribute('data-list-id');",
    "    var cardId = target.getAttribute('data-card-id');",
    "    if (listId) listId = parseInt(listId, 10);",
    "    if (cardId) cardId = parseInt(cardId, 10);",
    "",
    "    switch(action) {",
    "      case 'rename-list': startRenameList(listId, target); break;",
    "      case 'delete-list': startDeleteList(listId, target); break;",
    "      case 'show-add-card': showAddCardForm(listId, target); break;",
    "      case 'edit-card': startEditCard(cardId); break;",
    "      case 'delete-card': startDeleteCard(cardId, target); break;",
    "      case 'move-left': moveCardHorizontal(cardId, -1); break;",
    "      case 'move-right': moveCardHorizontal(cardId, 1); break;",
    "    }",
    "  });",
    "",
    "  // Add List",
    "  addListBtn.addEventListener('click', function() {",
    "    addListBtn.style.display = 'none';",
    "    var container = document.createElement('div');",
    "    container.className = 'inline-form';",
    "    container.style.cssText = 'position:absolute;top:12px;right:24px;width:240px;background:#fff;padding:12px;border-radius:8px;box-shadow:0 4px 12px rgba(0,0,0,0.15);z-index:20';",
    "    container.innerHTML = '<input type=\"text\" id=\"new-list-input\" placeholder=\"List title\" aria-label=\"New list title\">' +",
    "      '<div class=\"inline-form-row\">' +",
    "      '<button class=\"btn btn-primary btn-sm\" id=\"new-list-save\" aria-label=\"Save new list\">Add</button>' +",
    "      '<button class=\"btn btn-sm\" id=\"new-list-cancel\" aria-label=\"Cancel\">Cancel</button>' +",
    "      '</div>';",
    "    document.querySelector('.toolbar').appendChild(container);",
    "    var inp = document.getElementById('new-list-input');",
    "    inp.focus();",
    "    document.getElementById('new-list-save').addEventListener('click', function() {",
    "      var val = inp.value.trim();",
    "      if (!val) return;",
    "      api('POST', '/api/lists', { title: val })",
    "        .then(function() { container.remove(); addListBtn.style.display = ''; return loadBoard(); })",
    "        .catch(function(err) { showError(err.message); });",
    "    });",
    "    inp.addEventListener('keydown', function(e) {",
    "      if (e.key === 'Enter') document.getElementById('new-list-save').click();",
    "      if (e.key === 'Escape') document.getElementById('new-list-cancel').click();",
    "    });",
    "    document.getElementById('new-list-cancel').addEventListener('click', function() {",
    "      container.remove();",
    "      addListBtn.style.display = '';",
    "    });",
    "  });",
    "",
    "  // Rename List",
    "  function startRenameList(listId, el) {",
    "    var listIdx = getListIndex(listId);",
    "    if (listIdx < 0) return;",
    "    var currentTitle = boardData[listIdx].title;",
    "    var parent = el.parentElement;",
    "    var origHtml = parent.innerHTML;",
    "    parent.innerHTML = '<input type=\"text\" id=\"rename-list-input\" value=\"' + esc(currentTitle) + '\" aria-label=\"Rename list\" style=\"flex:1;color:#333\">' +",
    "      '<button class=\"btn btn-sm\" id=\"rename-list-save\" style=\"color:#333\" aria-label=\"Save\">Save</button>' +",
    "      '<button class=\"btn btn-sm\" id=\"rename-list-cancel\" style=\"color:#333\" aria-label=\"Cancel\">Cancel</button>';",
    "    var inp = document.getElementById('rename-list-input');",
    "    inp.focus();",
    "    inp.select();",
    "    document.getElementById('rename-list-save').addEventListener('click', function() {",
    "      var val = inp.value.trim();",
    "      if (!val) return;",
    "      api('PUT', '/api/lists/' + listId, { title: val })",
    "        .then(function() { return loadBoard(); })",
    "        .catch(function(err) { showError(err.message); parent.innerHTML = origHtml; });",
    "    });",
    "    inp.addEventListener('keydown', function(e) {",
    "      if (e.key === 'Enter') document.getElementById('rename-list-save').click();",
    "      if (e.key === 'Escape') document.getElementById('rename-list-cancel').click();",
    "    });",
    "    document.getElementById('rename-list-cancel').addEventListener('click', function() {",
    "      parent.innerHTML = origHtml;",
    "    });",
    "  }",
    "",
    "  // Delete List",
    "  function startDeleteList(listId, el) {",
    "    var parent = el.parentElement;",
    "    var origHtml = el.outerHTML;",
    "    el.outerHTML = '<div class=\"confirm-bar\" style=\"color:#fff\">' +",
    "      '<span>Delete list?</span>' +",
    "      '<button class=\"btn btn-sm btn-danger\" data-confirm-delete-list=\"' + listId + '\" aria-label=\"Confirm delete list\">Yes</button>' +",
    "      '<button class=\"btn btn-sm\" data-cancel-delete-list=\"' + listId + '\" aria-label=\"Cancel delete\">No</button>' +",
    "      '</div>';",
    "    parent.querySelector('[data-confirm-delete-list]').addEventListener('click', function() {",
    "      api('DELETE', '/api/lists/' + listId)",
    "        .then(function() { return loadBoard(); })",
    "        .catch(function(err) { showError(err.message); loadBoard(); });",
    "    });",
    "    parent.querySelector('[data-cancel-delete-list]').addEventListener('click', function() {",
    "      loadBoard();",
    "    });",
    "  }",
    "",
    "  // Add Card",
    "  function showAddCardForm(listId, btn) {",
    "    var footer = btn.parentElement;",
    "    footer.innerHTML = '<div class=\"inline-form\">' +",
    "      '<input type=\"text\" placeholder=\"Card title\" data-add-card-title=\"' + listId + '\" aria-label=\"Card title\">' +",
    "      '<div class=\"inline-form-row\">' +",
    "      '<button class=\"btn btn-primary btn-sm\" data-save-card=\"' + listId + '\" aria-label=\"Add card\">Add</button>' +",
    "      '<button class=\"btn btn-sm\" data-cancel-card=\"' + listId + '\" aria-label=\"Cancel\">Cancel</button>' +",
    "      '</div></div>';",
    "    var titleInp = footer.querySelector('[data-add-card-title]');",
    "    titleInp.focus();",
    "    footer.querySelector('[data-save-card]').addEventListener('click', function() {",
    "      var title = titleInp.value.trim();",
    "      if (!title) return;",
    "      api('POST', '/api/cards', { list_id: listId, title: title })",
    "        .then(function() { return loadBoard(); })",
    "        .catch(function(err) { showError(err.message); });",
    "    });",
    "    titleInp.addEventListener('keydown', function(e) {",
    "      if (e.key === 'Enter') footer.querySelector('[data-save-card]').click();",
    "      if (e.key === 'Escape') footer.querySelector('[data-cancel-card]').click();",
    "    });",
    "    footer.querySelector('[data-cancel-card]').addEventListener('click', function() {",
    "      loadBoard();",
    "    });",
    "  }",
    "",
    "  // Edit Card",
    "  function startEditCard(cardId) {",
    "    var info = findCard(cardId);",
    "    if (!info) return;",
    "    var card = info.card;",
    "    var cardEl = boardEl.querySelector('.card[data-card-id=\"' + cardId + '\"]');",
    "    if (!cardEl) return;",
    "    cardEl.setAttribute('draggable', 'false');",
    "    cardEl.innerHTML = '<div class=\"inline-form\">' +",
    "      '<input type=\"text\" value=\"' + esc(card.title) + '\" data-edit-title=\"' + cardId + '\" aria-label=\"Card title\">' +",
    "      '<textarea data-edit-desc=\"' + cardId + '\" aria-label=\"Card description\">' + esc(card.description || '') + '</textarea>' +",
    "      '<div class=\"inline-form-row\">' +",
    "      '<button class=\"btn btn-primary btn-sm\" data-save-edit=\"' + cardId + '\" aria-label=\"Save card\">Save</button>' +",
    "      '<button class=\"btn btn-sm\" data-cancel-edit=\"' + cardId + '\" aria-label=\"Cancel edit\">Cancel</button>' +",
    "      '</div></div>';",
    "    cardEl.querySelector('[data-edit-title]').focus();",
    "    cardEl.querySelector('[data-save-edit]').addEventListener('click', function() {",
    "      var t = cardEl.querySelector('[data-edit-title]').value.trim();",
    "      var d = cardEl.querySelector('[data-edit-desc]').value.trim();",
    "      if (!t) return;",
    "      api('PUT', '/api/cards/' + cardId, { title: t, description: d })",
    "        .then(function() { return loadBoard(); })",
    "        .catch(function(err) { showError(err.message); });",
    "    });",
    "    cardEl.querySelector('[data-edit-title]').addEventListener('keydown', function(e) {",
    "      if (e.key === 'Enter') cardEl.querySelector('[data-save-edit]').click();",
    "      if (e.key === 'Escape') cardEl.querySelector('[data-cancel-edit]').click();",
    "    });",
    "    cardEl.querySelector('[data-cancel-edit]').addEventListener('click', function() {",
    "      loadBoard();",
    "    });",
    "  }",
    "",
    "  // Delete Card",
    "  function startDeleteCard(cardId, el) {",
    "    var cardEl = el.closest('.card');",
    "    var actionsEl = cardEl.querySelector('.card-actions');",
    "    actionsEl.innerHTML = '<div class=\"confirm-bar\">' +",
    "      '<span>Are you sure?</span>' +",
    "      '<button class=\"btn btn-sm btn-danger\" data-confirm-delete-card=\"' + cardId + '\" aria-label=\"Confirm delete card\">Yes</button>' +",
    "      '<button class=\"btn btn-sm\" data-cancel-delete-card=\"' + cardId + '\" aria-label=\"Cancel delete card\">No</button>' +",
    "      '</div>';",
    "    actionsEl.querySelector('[data-confirm-delete-card]').addEventListener('click', function() {",
    "      api('DELETE', '/api/cards/' + cardId)",
    "        .then(function() { return loadBoard(); })",
    "        .catch(function(err) { showError(err.message); loadBoard(); });",
    "    });",
    "    actionsEl.querySelector('[data-cancel-delete-card]').addEventListener('click', function() {",
    "      loadBoard();",
    "    });",
    "  }",
    "",
    "  // Move Card Left/Right",
    "  function moveCardHorizontal(cardId, direction) {",
    "    var info = findCard(cardId);",
    "    if (!info) return;",
    "    var targetIdx = info.listIdx + direction;",
    "    if (targetIdx < 0 || targetIdx >= boardData.length) return;",
    "    var targetList = boardData[targetIdx];",
    "    var targetPos = (targetList.cards || []).length;",
    "    api('POST', '/api/cards/' + cardId + '/move', { target_list_id: targetList.id, position: targetPos })",
    "      .then(function() { return loadBoard(); })",
    "      .catch(function(err) { showError('Move failed: ' + err.message); });",
    "  }",
    "",
    "  // Initial load",
    "  loadBoard();",
    "",
    "})();",
  ].join("\n");
}
